name: design_test
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg:
  provider: ^6.0.5
  flutter_screenutil: ^5.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/

  
  fonts:
    - family: Avenir
      fonts:
        - asset: assets/font/avenir/AvenirLTProMedium.otf
        - asset: assets/font/avenir/AvenirLTProLight.otf
        - asset: assets/font/avenir/AvenirLTProBlack.otf
        - asset: assets/font/avenir/AvenirLTProHeavy.otf
        - asset: assets/font/avenir/AvenirLTProBook.otf
